/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quicktables;

import java.util.*;
import java.io.*;
import javax.swing.JTextArea;
/**
 *
 * @author David
 */
public class UI extends javax.swing.JFrame {

    Schedule schedule;
            
    /**
     * Creates new form NewJFrame
     */
    public UI() {
        initComponents();
    }
    
    private void loadData(){
        
        try{
            ObjectInputStream in = new ObjectInputStream(new FileInputStream("timetable.ser"));
            schedule = (Schedule)in.readObject();
            
            schedule.getDay(1);
            displayInfo(Day1Homeroom, schedule.getDay(1), 1);
            
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    private void displayInfo(JTextArea displayBox, Day day, int period){
        Course course = day.getCourse(period);
        displayBox.setText(null);
        displayBox.append(course.getCourseCode());
        displayBox.append("\n");
        displayBox.append(course.getCourseName());
        displayBox.append("\n");
        displayBox.append(course.getRoom());
        displayBox.append("\n");
        displayBox.append(course.getTeacher());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHomeroom = new javax.swing.JLabel();
        lblSchoolAndYear = new javax.swing.JLabel();
        btnNameAndGrade = new javax.swing.JLabel();
        lblBreak1 = new javax.swing.JLabel();
        lblBreak2 = new javax.swing.JLabel();
        lblDay1 = new javax.swing.JLabel();
        lblDay2 = new javax.swing.JLabel();
        lblDay3 = new javax.swing.JLabel();
        lblDay4 = new javax.swing.JLabel();
        lblDay5 = new javax.swing.JLabel();
        lblDay6 = new javax.swing.JLabel();
        lblDay7 = new javax.swing.JLabel();
        lblDay8 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 32767));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 0), new java.awt.Dimension(70, 32767));
        lblPeriod1 = new javax.swing.JLabel();
        lblPeriod2 = new javax.swing.JLabel();
        lblPeriod3 = new javax.swing.JLabel();
        lblPeriod4 = new javax.swing.JLabel();
        lblPeriod5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Day1Homeroom = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Day2Homeroom = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Day3Homeroom = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Day4Homeroom = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Day5Homeroom = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        Day6Homeroom = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        Day7Homeroom = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        Day8Homeroom = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        Day8Period1 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        Day7Period1 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        Day6Period1 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        Day5Period1 = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        Day4Period1 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        Day3 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        Day2Period1 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        Day1Period1 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        Day1Period2 = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        Day2Period2 = new javax.swing.JTextArea();
        jScrollPane19 = new javax.swing.JScrollPane();
        Day3Period2 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        Day4Period2 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        Day5Period2 = new javax.swing.JTextArea();
        jScrollPane22 = new javax.swing.JScrollPane();
        Day6Period2 = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        Day7Period2 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        Day8Period2 = new javax.swing.JTextArea();
        jScrollPane41 = new javax.swing.JScrollPane();
        Day1Period3 = new javax.swing.JTextArea();
        jScrollPane42 = new javax.swing.JScrollPane();
        Day2Period3 = new javax.swing.JTextArea();
        jScrollPane43 = new javax.swing.JScrollPane();
        Day3Period3 = new javax.swing.JTextArea();
        jScrollPane44 = new javax.swing.JScrollPane();
        Day4Period3 = new javax.swing.JTextArea();
        jScrollPane45 = new javax.swing.JScrollPane();
        Day5Period3 = new javax.swing.JTextArea();
        jScrollPane46 = new javax.swing.JScrollPane();
        Day6Period3 = new javax.swing.JTextArea();
        jScrollPane47 = new javax.swing.JScrollPane();
        Day7Period3 = new javax.swing.JTextArea();
        jScrollPane48 = new javax.swing.JScrollPane();
        Day8Period3 = new javax.swing.JTextArea();
        jScrollPane25 = new javax.swing.JScrollPane();
        Day1Period4 = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        Day2Period4 = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        Day3Period4 = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        Day4Period4 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        Day5Period4 = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        Day6Period4 = new javax.swing.JTextArea();
        jScrollPane31 = new javax.swing.JScrollPane();
        Day7Period4 = new javax.swing.JTextArea();
        jScrollPane32 = new javax.swing.JScrollPane();
        Day8Period4 = new javax.swing.JTextArea();
        jScrollPane33 = new javax.swing.JScrollPane();
        Day1Period5 = new javax.swing.JTextArea();
        jScrollPane34 = new javax.swing.JScrollPane();
        Day2Period5 = new javax.swing.JTextArea();
        jScrollPane35 = new javax.swing.JScrollPane();
        Day3Period5 = new javax.swing.JTextArea();
        jScrollPane36 = new javax.swing.JScrollPane();
        Day4Period5 = new javax.swing.JTextArea();
        jScrollPane37 = new javax.swing.JScrollPane();
        Day5Period5 = new javax.swing.JTextArea();
        jScrollPane38 = new javax.swing.JScrollPane();
        Day6Period5 = new javax.swing.JTextArea();
        jScrollPane39 = new javax.swing.JScrollPane();
        Day7Period5 = new javax.swing.JTextArea();
        jScrollPane40 = new javax.swing.JScrollPane();
        Day8Period5 = new javax.swing.JTextArea();
        btnLoad = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHomeroom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHomeroom.setText("Homeroom");

        lblSchoolAndYear.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblSchoolAndYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSchoolAndYear.setText("<School and Year>");

        btnNameAndGrade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNameAndGrade.setText("<Name and Grade>");

        lblBreak1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblBreak1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBreak1.setText("<Break 1>");

        lblBreak2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblBreak2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBreak2.setText("<Break 2>");

        lblDay1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDay1.setText("Day 1");

        lblDay2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDay2.setText("Day 2");

        lblDay3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDay3.setText("Day 3");

        lblDay4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDay4.setText("Day 4");

        lblDay5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDay5.setText("Day 5");

        lblDay6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDay6.setText("Day 6");

        lblDay7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDay7.setText("Day 7");

        lblDay8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDay8.setText("Day 8");

        lblPeriod1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPeriod1.setText("Period 1");

        lblPeriod2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPeriod2.setText("Period 2");

        lblPeriod3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPeriod3.setText("Period 3");

        lblPeriod4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPeriod4.setText("Period 4");

        lblPeriod5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPeriod5.setText("Period 5");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day1Homeroom.setEditable(false);
        Day1Homeroom.setColumns(20);
        Day1Homeroom.setLineWrap(true);
        Day1Homeroom.setRows(5);
        Day1Homeroom.setAutoscrolls(false);
        jScrollPane1.setViewportView(Day1Homeroom);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day2Homeroom.setEditable(false);
        Day2Homeroom.setColumns(20);
        Day2Homeroom.setLineWrap(true);
        Day2Homeroom.setRows(5);
        Day2Homeroom.setAutoscrolls(false);
        jScrollPane2.setViewportView(Day2Homeroom);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day3Homeroom.setEditable(false);
        Day3Homeroom.setColumns(20);
        Day3Homeroom.setLineWrap(true);
        Day3Homeroom.setRows(5);
        Day3Homeroom.setAutoscrolls(false);
        jScrollPane3.setViewportView(Day3Homeroom);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day4Homeroom.setEditable(false);
        Day4Homeroom.setColumns(20);
        Day4Homeroom.setLineWrap(true);
        Day4Homeroom.setRows(5);
        Day4Homeroom.setAutoscrolls(false);
        jScrollPane4.setViewportView(Day4Homeroom);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day5Homeroom.setEditable(false);
        Day5Homeroom.setColumns(20);
        Day5Homeroom.setLineWrap(true);
        Day5Homeroom.setRows(5);
        Day5Homeroom.setAutoscrolls(false);
        jScrollPane5.setViewportView(Day5Homeroom);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day6Homeroom.setEditable(false);
        Day6Homeroom.setColumns(20);
        Day6Homeroom.setLineWrap(true);
        Day6Homeroom.setRows(5);
        Day6Homeroom.setAutoscrolls(false);
        jScrollPane6.setViewportView(Day6Homeroom);

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day7Homeroom.setEditable(false);
        Day7Homeroom.setColumns(20);
        Day7Homeroom.setLineWrap(true);
        Day7Homeroom.setRows(5);
        Day7Homeroom.setAutoscrolls(false);
        jScrollPane7.setViewportView(Day7Homeroom);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day8Homeroom.setEditable(false);
        Day8Homeroom.setColumns(20);
        Day8Homeroom.setLineWrap(true);
        Day8Homeroom.setRows(5);
        Day8Homeroom.setAutoscrolls(false);
        jScrollPane8.setViewportView(Day8Homeroom);

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day8Period1.setEditable(false);
        Day8Period1.setColumns(20);
        Day8Period1.setLineWrap(true);
        Day8Period1.setRows(5);
        Day8Period1.setAutoscrolls(false);
        jScrollPane9.setViewportView(Day8Period1);

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day7Period1.setEditable(false);
        Day7Period1.setColumns(20);
        Day7Period1.setLineWrap(true);
        Day7Period1.setRows(5);
        Day7Period1.setAutoscrolls(false);
        jScrollPane10.setViewportView(Day7Period1);

        jScrollPane11.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane11.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day6Period1.setEditable(false);
        Day6Period1.setColumns(20);
        Day6Period1.setLineWrap(true);
        Day6Period1.setRows(5);
        Day6Period1.setAutoscrolls(false);
        jScrollPane11.setViewportView(Day6Period1);

        jScrollPane12.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane12.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day5Period1.setEditable(false);
        Day5Period1.setColumns(20);
        Day5Period1.setLineWrap(true);
        Day5Period1.setRows(5);
        Day5Period1.setAutoscrolls(false);
        jScrollPane12.setViewportView(Day5Period1);

        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day4Period1.setEditable(false);
        Day4Period1.setColumns(20);
        Day4Period1.setLineWrap(true);
        Day4Period1.setRows(5);
        Day4Period1.setAutoscrolls(false);
        jScrollPane13.setViewportView(Day4Period1);

        jScrollPane14.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane14.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day3.setEditable(false);
        Day3.setColumns(20);
        Day3.setLineWrap(true);
        Day3.setRows(5);
        Day3.setAutoscrolls(false);
        jScrollPane14.setViewportView(Day3);

        jScrollPane15.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane15.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day2Period1.setEditable(false);
        Day2Period1.setColumns(20);
        Day2Period1.setLineWrap(true);
        Day2Period1.setRows(5);
        Day2Period1.setAutoscrolls(false);
        jScrollPane15.setViewportView(Day2Period1);

        jScrollPane16.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane16.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day1Period1.setEditable(false);
        Day1Period1.setColumns(20);
        Day1Period1.setLineWrap(true);
        Day1Period1.setRows(5);
        Day1Period1.setAutoscrolls(false);
        jScrollPane16.setViewportView(Day1Period1);

        jScrollPane17.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane17.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day1Period2.setEditable(false);
        Day1Period2.setColumns(20);
        Day1Period2.setLineWrap(true);
        Day1Period2.setRows(5);
        Day1Period2.setAutoscrolls(false);
        jScrollPane17.setViewportView(Day1Period2);

        jScrollPane18.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane18.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day2Period2.setEditable(false);
        Day2Period2.setColumns(20);
        Day2Period2.setLineWrap(true);
        Day2Period2.setRows(5);
        Day2Period2.setAutoscrolls(false);
        jScrollPane18.setViewportView(Day2Period2);

        jScrollPane19.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane19.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day3Period2.setEditable(false);
        Day3Period2.setColumns(20);
        Day3Period2.setLineWrap(true);
        Day3Period2.setRows(5);
        Day3Period2.setAutoscrolls(false);
        jScrollPane19.setViewportView(Day3Period2);

        jScrollPane20.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane20.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day4Period2.setEditable(false);
        Day4Period2.setColumns(20);
        Day4Period2.setLineWrap(true);
        Day4Period2.setRows(5);
        Day4Period2.setAutoscrolls(false);
        jScrollPane20.setViewportView(Day4Period2);

        jScrollPane21.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane21.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day5Period2.setEditable(false);
        Day5Period2.setColumns(20);
        Day5Period2.setLineWrap(true);
        Day5Period2.setRows(5);
        Day5Period2.setAutoscrolls(false);
        jScrollPane21.setViewportView(Day5Period2);

        jScrollPane22.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane22.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day6Period2.setEditable(false);
        Day6Period2.setColumns(20);
        Day6Period2.setLineWrap(true);
        Day6Period2.setRows(5);
        Day6Period2.setAutoscrolls(false);
        jScrollPane22.setViewportView(Day6Period2);

        jScrollPane23.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane23.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day7Period2.setEditable(false);
        Day7Period2.setColumns(20);
        Day7Period2.setLineWrap(true);
        Day7Period2.setRows(5);
        Day7Period2.setAutoscrolls(false);
        jScrollPane23.setViewportView(Day7Period2);

        jScrollPane24.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane24.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day8Period2.setEditable(false);
        Day8Period2.setColumns(20);
        Day8Period2.setLineWrap(true);
        Day8Period2.setRows(5);
        Day8Period2.setAutoscrolls(false);
        jScrollPane24.setViewportView(Day8Period2);

        jScrollPane41.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane41.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day1Period3.setEditable(false);
        Day1Period3.setColumns(20);
        Day1Period3.setLineWrap(true);
        Day1Period3.setRows(5);
        Day1Period3.setAutoscrolls(false);
        jScrollPane41.setViewportView(Day1Period3);

        jScrollPane42.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane42.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day2Period3.setEditable(false);
        Day2Period3.setColumns(20);
        Day2Period3.setLineWrap(true);
        Day2Period3.setRows(5);
        Day2Period3.setAutoscrolls(false);
        jScrollPane42.setViewportView(Day2Period3);

        jScrollPane43.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane43.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day3Period3.setEditable(false);
        Day3Period3.setColumns(20);
        Day3Period3.setLineWrap(true);
        Day3Period3.setRows(5);
        Day3Period3.setAutoscrolls(false);
        jScrollPane43.setViewportView(Day3Period3);

        jScrollPane44.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane44.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day4Period3.setEditable(false);
        Day4Period3.setColumns(20);
        Day4Period3.setLineWrap(true);
        Day4Period3.setRows(5);
        Day4Period3.setAutoscrolls(false);
        jScrollPane44.setViewportView(Day4Period3);

        jScrollPane45.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane45.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day5Period3.setEditable(false);
        Day5Period3.setColumns(20);
        Day5Period3.setLineWrap(true);
        Day5Period3.setRows(5);
        Day5Period3.setAutoscrolls(false);
        jScrollPane45.setViewportView(Day5Period3);

        jScrollPane46.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane46.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day6Period3.setEditable(false);
        Day6Period3.setColumns(20);
        Day6Period3.setLineWrap(true);
        Day6Period3.setRows(5);
        Day6Period3.setAutoscrolls(false);
        jScrollPane46.setViewportView(Day6Period3);

        jScrollPane47.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane47.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day7Period3.setEditable(false);
        Day7Period3.setColumns(20);
        Day7Period3.setLineWrap(true);
        Day7Period3.setRows(5);
        Day7Period3.setAutoscrolls(false);
        jScrollPane47.setViewportView(Day7Period3);

        jScrollPane48.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane48.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day8Period3.setEditable(false);
        Day8Period3.setColumns(20);
        Day8Period3.setLineWrap(true);
        Day8Period3.setRows(5);
        Day8Period3.setAutoscrolls(false);
        jScrollPane48.setViewportView(Day8Period3);

        jScrollPane25.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane25.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day1Period4.setEditable(false);
        Day1Period4.setColumns(20);
        Day1Period4.setLineWrap(true);
        Day1Period4.setRows(5);
        Day1Period4.setAutoscrolls(false);
        jScrollPane25.setViewportView(Day1Period4);

        jScrollPane26.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane26.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day2Period4.setEditable(false);
        Day2Period4.setColumns(20);
        Day2Period4.setLineWrap(true);
        Day2Period4.setRows(5);
        Day2Period4.setAutoscrolls(false);
        jScrollPane26.setViewportView(Day2Period4);

        jScrollPane27.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane27.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day3Period4.setEditable(false);
        Day3Period4.setColumns(20);
        Day3Period4.setLineWrap(true);
        Day3Period4.setRows(5);
        Day3Period4.setAutoscrolls(false);
        jScrollPane27.setViewportView(Day3Period4);

        jScrollPane28.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane28.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day4Period4.setEditable(false);
        Day4Period4.setColumns(20);
        Day4Period4.setLineWrap(true);
        Day4Period4.setRows(5);
        Day4Period4.setAutoscrolls(false);
        jScrollPane28.setViewportView(Day4Period4);

        jScrollPane29.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane29.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day5Period4.setEditable(false);
        Day5Period4.setColumns(20);
        Day5Period4.setLineWrap(true);
        Day5Period4.setRows(5);
        Day5Period4.setAutoscrolls(false);
        jScrollPane29.setViewportView(Day5Period4);

        jScrollPane30.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane30.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day6Period4.setEditable(false);
        Day6Period4.setColumns(20);
        Day6Period4.setLineWrap(true);
        Day6Period4.setRows(5);
        Day6Period4.setAutoscrolls(false);
        jScrollPane30.setViewportView(Day6Period4);

        jScrollPane31.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane31.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day7Period4.setEditable(false);
        Day7Period4.setColumns(20);
        Day7Period4.setLineWrap(true);
        Day7Period4.setRows(5);
        Day7Period4.setAutoscrolls(false);
        jScrollPane31.setViewportView(Day7Period4);

        jScrollPane32.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane32.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day8Period4.setEditable(false);
        Day8Period4.setColumns(20);
        Day8Period4.setLineWrap(true);
        Day8Period4.setRows(5);
        Day8Period4.setAutoscrolls(false);
        jScrollPane32.setViewportView(Day8Period4);

        jScrollPane33.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane33.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day1Period5.setEditable(false);
        Day1Period5.setColumns(20);
        Day1Period5.setLineWrap(true);
        Day1Period5.setRows(5);
        Day1Period5.setAutoscrolls(false);
        jScrollPane33.setViewportView(Day1Period5);

        jScrollPane34.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane34.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day2Period5.setEditable(false);
        Day2Period5.setColumns(20);
        Day2Period5.setLineWrap(true);
        Day2Period5.setRows(5);
        Day2Period5.setAutoscrolls(false);
        jScrollPane34.setViewportView(Day2Period5);

        jScrollPane35.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane35.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day3Period5.setEditable(false);
        Day3Period5.setColumns(20);
        Day3Period5.setLineWrap(true);
        Day3Period5.setRows(5);
        Day3Period5.setAutoscrolls(false);
        jScrollPane35.setViewportView(Day3Period5);

        jScrollPane36.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane36.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day4Period5.setEditable(false);
        Day4Period5.setColumns(20);
        Day4Period5.setLineWrap(true);
        Day4Period5.setRows(5);
        Day4Period5.setAutoscrolls(false);
        jScrollPane36.setViewportView(Day4Period5);

        jScrollPane37.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane37.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day5Period5.setEditable(false);
        Day5Period5.setColumns(20);
        Day5Period5.setLineWrap(true);
        Day5Period5.setRows(5);
        Day5Period5.setAutoscrolls(false);
        jScrollPane37.setViewportView(Day5Period5);

        jScrollPane38.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane38.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day6Period5.setEditable(false);
        Day6Period5.setColumns(20);
        Day6Period5.setLineWrap(true);
        Day6Period5.setRows(5);
        Day6Period5.setAutoscrolls(false);
        jScrollPane38.setViewportView(Day6Period5);

        jScrollPane39.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane39.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day7Period5.setEditable(false);
        Day7Period5.setColumns(20);
        Day7Period5.setLineWrap(true);
        Day7Period5.setRows(5);
        Day7Period5.setAutoscrolls(false);
        jScrollPane39.setViewportView(Day7Period5);

        jScrollPane40.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane40.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        Day8Period5.setEditable(false);
        Day8Period5.setColumns(20);
        Day8Period5.setLineWrap(true);
        Day8Period5.setRows(5);
        Day8Period5.setAutoscrolls(false);
        jScrollPane40.setViewportView(Day8Period5);

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblBreak1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNameAndGrade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCreate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPeriod1)
                                    .addComponent(lblPeriod2)
                                    .addComponent(lblPeriod3)
                                    .addComponent(lblPeriod4)
                                    .addComponent(lblPeriod5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane48, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblHomeroom)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(lblDay1)
                                                .addGap(4, 4, 4)
                                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDay2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDay3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDay4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDay5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDay6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDay7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(filler7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDay8))))
                                    .addComponent(btnLoad))))
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBreak2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(310, Short.MAX_VALUE)
                    .addComponent(lblSchoolAndYear, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(240, 240, 240)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNameAndGrade)
                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDay1)
                            .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDay7)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDay3)
                            .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDay4)
                            .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDay5)
                            .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDay6)
                            .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filler7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDay8)
                            .addComponent(lblDay2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblHomeroom)
                                .addGap(16, 16, 16)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblPeriod1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblPeriod2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBreak1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane48, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane41, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane42, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane43, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane44, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane45, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane46, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane47, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblPeriod3)))
                .addGap(7, 7, 7)
                .addComponent(lblBreak2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane31, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPeriod4)
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane40, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane37, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane38, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPeriod5)
                        .addGap(23, 23, 23)))
                .addGap(33, 33, 33))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(lblSchoolAndYear)
                    .addContainerGap(550, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CreateUI();
    }//GEN-LAST:event_btnCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Day1Homeroom;
    private javax.swing.JTextArea Day1Period1;
    private javax.swing.JTextArea Day1Period2;
    private javax.swing.JTextArea Day1Period3;
    private javax.swing.JTextArea Day1Period4;
    private javax.swing.JTextArea Day1Period5;
    private javax.swing.JTextArea Day2Homeroom;
    private javax.swing.JTextArea Day2Period1;
    private javax.swing.JTextArea Day2Period2;
    private javax.swing.JTextArea Day2Period3;
    private javax.swing.JTextArea Day2Period4;
    private javax.swing.JTextArea Day2Period5;
    private javax.swing.JTextArea Day3;
    private javax.swing.JTextArea Day3Homeroom;
    private javax.swing.JTextArea Day3Period2;
    private javax.swing.JTextArea Day3Period3;
    private javax.swing.JTextArea Day3Period4;
    private javax.swing.JTextArea Day3Period5;
    private javax.swing.JTextArea Day4Homeroom;
    private javax.swing.JTextArea Day4Period1;
    private javax.swing.JTextArea Day4Period2;
    private javax.swing.JTextArea Day4Period3;
    private javax.swing.JTextArea Day4Period4;
    private javax.swing.JTextArea Day4Period5;
    private javax.swing.JTextArea Day5Homeroom;
    private javax.swing.JTextArea Day5Period1;
    private javax.swing.JTextArea Day5Period2;
    private javax.swing.JTextArea Day5Period3;
    private javax.swing.JTextArea Day5Period4;
    private javax.swing.JTextArea Day5Period5;
    private javax.swing.JTextArea Day6Homeroom;
    private javax.swing.JTextArea Day6Period1;
    private javax.swing.JTextArea Day6Period2;
    private javax.swing.JTextArea Day6Period3;
    private javax.swing.JTextArea Day6Period4;
    private javax.swing.JTextArea Day6Period5;
    private javax.swing.JTextArea Day7Homeroom;
    private javax.swing.JTextArea Day7Period1;
    private javax.swing.JTextArea Day7Period2;
    private javax.swing.JTextArea Day7Period3;
    private javax.swing.JTextArea Day7Period4;
    private javax.swing.JTextArea Day7Period5;
    private javax.swing.JTextArea Day8Homeroom;
    private javax.swing.JTextArea Day8Period1;
    private javax.swing.JTextArea Day8Period2;
    private javax.swing.JTextArea Day8Period3;
    private javax.swing.JTextArea Day8Period4;
    private javax.swing.JTextArea Day8Period5;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnLoad;
    private javax.swing.JLabel btnNameAndGrade;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JScrollPane jScrollPane48;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblBreak1;
    private javax.swing.JLabel lblBreak2;
    private javax.swing.JLabel lblDay1;
    private javax.swing.JLabel lblDay2;
    private javax.swing.JLabel lblDay3;
    private javax.swing.JLabel lblDay4;
    private javax.swing.JLabel lblDay5;
    private javax.swing.JLabel lblDay6;
    private javax.swing.JLabel lblDay7;
    private javax.swing.JLabel lblDay8;
    private javax.swing.JLabel lblHomeroom;
    private javax.swing.JLabel lblPeriod1;
    private javax.swing.JLabel lblPeriod2;
    private javax.swing.JLabel lblPeriod3;
    private javax.swing.JLabel lblPeriod4;
    private javax.swing.JLabel lblPeriod5;
    private javax.swing.JLabel lblSchoolAndYear;
    // End of variables declaration//GEN-END:variables
}
